apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app8
  template:
      metadata:
        labels:
          app: my-app8
      spec:
         containers:
          - name: my-container
            image: nginx
            ports: 
              - containerPort: 80
